a = input('Digite algo: ')
print('O tipo primitivo do valor digitado é ',type(a))
print('Só tem espaços? ',a.isspace())
print('É um número? ',a.isnumeric())
print('É alfabético? ',a.isalpha())
print('É alfanumérico? ',a.isalnum())
print('Todas as letras são maiúsculas? ',a.isupper())
print('Todas as letras são minúsculas? ',a.islower())
print('Está capitalizado? ',a.istitle())
